<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-R9EM6AG" name="testcases.Mandatorystartdestination" tests="1" failures="0" timestamp="25 Feb 2020 18:05:20 GMT" time="0.047" errors="1">
  <testcase name="mandatorystartdestination" time="0.047" classname="testcases.Mandatorystartdestination">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: mandatorystartdestination([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)sudip,(java.lang.String)dutta,(java.lang.String)Albania,(java.lang.String)Address1,(java.lang.String)9051406767,(java.lang.String)F,(java.lang.String)24-02-1990,(java.lang.String)sudipdutta710@gmail.com,(java.lang.String)dutsudi,(java.lang.String)alokRanjan,(java.lang.String)alokRanjan,(java.lang.String)N,(java.lang.String)Y]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: mandatorystartdestination([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)sudip,(java.lang.String)dutta,(java.lang.String)Albania,(java.lang.String)Address1,(java.lang.String)9051406767,(java.lang.String)F,(java.lang.String)24-02-1990,(java.lang.String)sudipdutta710@gmail.com,(java.lang.String)dutsudi,(java.lang.String)alokRanjan,(java.lang.String)alokRanjan,(java.lang.String)N,(java.lang.String)Y]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:49)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1187)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- mandatorystartdestination -->
</testsuite> <!-- testcases.Mandatorystartdestination -->
